-- Seed de la banque de contenu (généré depuis content_bank.json)
insert into public.content_items (content_type, category, subcategory, mode_scope, type, level, text, answer, variants, explanation, manga_series, temps_suggere) values
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'Quelle est la capitale de la France ?', 'Paris', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'devinette', 'facile', 'Quel héros porte un costume rouge et bleu et lance des toiles ?', 'Spider-Man', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'En quelle année a commencé la Première Guerre mondiale ?', '1914', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quel est le plus grand océan du monde ?', 'Pacifique', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'Quel traité a mis fin à la Première Guerre mondiale ?', 'Traité de Versailles', NULL, NULL, NULL, 30),
('question', 'general', 'manga', 'tous', 'reponse_libre', 'impossible', 'Dans Fairy Tail, quel personnage utilise un pistolet magique comme arme principale ?', 'Arzak Connel', NULL, NULL, 'Fairy Tail', 30),
('question', 'general', 'manga', 'tous', 'reponse_libre', 'impossible', 'Dans Fairy Tail, comment s''appelle l''armure qu''Erza invoque et qui n''a pas été portée depuis 10 ans ?', 'Nakagami no Yoroi', NULL, NULL, 'Fairy Tail', 30),
('question', 'general', 'sciences', 'tous', 'qcm', 'facile', 'Combien de planètes compte le système solaire ?', '8', '{"choix":["6","7","8","9"]}'::jsonb, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'vrai_faux', 'moyen', 'Le corps humain contient plus de bactéries que de cellules humaines.', 'Vrai (à peu près à égalité selon les études récentes)', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'qcm', 'facile', 'Combien de joueurs sur le terrain dans une équipe de foot (hors gardien) ?', '10', '{"choix":["9","10","11","12"]}'::jsonb, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'devinette', 'moyen', 'Quel compositeur allemand est devenu sourd à la fin de sa vie ?', 'Beethoven', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'difficile', 'Quel peintre néerlandais s''est coupé une partie de l''oreille ?', 'Van Gogh', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'moyen', 'Les flamants roses naissent gris.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'manga', 'tous', 'qcm', 'facile', 'Quel est le rêve de Monkey D. Luffy dans One Piece ?', 'Devenir le roi des pirates', '{"choix":["Devenir le roi des pirates","Devenir le meilleur épéiste","Trouver un trésor","Devenir Hokage"]}'::jsonb, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quelle est la capitale du Kazakhstan ?', 'Astana', NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Quelle est, selon toi, la chose la plus importante dans la vie ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Penses-tu qu''il faut toujours dire la vérité, même si ça blesse ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', 'Si tu pouvais savoir la date de ta mort, voudrais-tu la connaître ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'moyen', 'Es-tu pour ou contre le vote obligatoire ? Pourquoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'difficile', 'Penses-tu que la démocratie est le meilleur système politique ? Pourquoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', '« L''enfer, c''est les autres. » - Sartre. Es-tu d''accord avec cette phrase ? Pourquoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'facile', 'Si tu devais garder un seul souvenir de ta vie, lequel choisirais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'facile', 'Quel est ton souvenir préféré de notre rencontre ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'amis', 'reponse_libre', 'facile', 'Quel est le souvenir le plus drôle qu''on a vécu ensemble ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : la montagne ou la mer ?', NULL, '{"choix":["Montagne","Mer"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'couple', 'qcm', 'moyen', 'Tu préfères : un dîner romantique ou un week-end aventure ?', NULL, '{"choix":["Dîner romantique","Week-end aventure"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'facile', 'Qui de nous deux est le plus jaloux/se ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'amis', 'qcm', 'facile', 'Qui du groupe est le plus susceptible d''arriver en retard ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'facile', 'Si tu étais un objet de la maison, lequel serais-tu et pourquoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'moyen', 'Si tu devais échanger de corps avec un animal pour une journée, lequel choisirais-tu ?', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'defis_gages', 'couple', 'action', 'facile', 'Fais un compliment sincère à ton/ta partenaire sans utiliser le mot ''beau/belle''.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'defis_gages', 'amis', 'action', 'moyen', 'Imite un membre du groupe pendant 30 secondes, les autres doivent deviner qui.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'defis_gages', 'solo', 'action', 'facile', 'Écris un mot doux que tu pourrais envoyer à quelqu''un qui compte pour toi.', NULL, NULL, NULL, NULL, 120),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'facile', 'Je n''ai pas de bouche mais je peux parler, pas de corps mais je peux répondre. Qui suis-je ?', 'Un écho', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'moyen', 'Plus j''en enlève, plus je deviens grand. Qu''est-ce que je suis ?', 'Un trou', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'code_4_chiffres', 'difficile', 'Trouvez le code à 4 chiffres : la somme des chiffres fait 12, le premier chiffre est le double du dernier, et le code est pair.', '4620', NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'moyen', 'Si tu devais recommencer ta vie, changerais-tu quelque chose ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'enfance', 'tous', 'reponse_libre', 'facile', 'Quel est ton souvenir d''enfance préféré ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'reves', 'tous', 'reponse_libre', 'moyen', 'Quel est un rêve que tu n''as jamais réalisé mais que tu aimerais accomplir ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'peurs', 'tous', 'reponse_libre', 'moyen', 'Quelle est ta plus grande peur ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'difficile', 'Quelle valeur refuserais-tu de sacrifier, même pour de l''argent ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'moyen', 'Qu''est-ce qui t''a fait tomber amoureux/se de moi ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amitie', 'amis', 'reponse_libre', 'moyen', 'Qu''est-ce que tu apprécies le plus dans notre amitié ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'futur', 'tous', 'reponse_libre', 'moyen', 'Où te vois-tu dans 10 ans ?', NULL, NULL, NULL, NULL, 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'facile', 'Quel est le nom du bateau de l''équipage de Luffy après le Merry ?', 'Thousand Sunny', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'moyen', 'Comment s''appelle le démon renard scellé en Naruto ?', 'Kurama', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'difficile', 'Quel est le vrai nom du Titan Colossal ?', 'Bertholdt Hoover', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'demon_slayer', 'tous', 'reponse_libre', 'facile', 'Quelle est la couleur des yeux de Nezuko lorsqu''elle est en démon ?', 'Rose/rouge', NULL, NULL, 'Demon Slayer', 30),
('question', 'manga', 'fairy_tail', 'tous', 'reponse_libre', 'moyen', 'Quelle guilde rivale de Fairy Tail apparaît lors du Grand Jeu Magique ?', 'Sabertooth', NULL, NULL, 'Fairy Tail', 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'Qui était le premier président de la République française ?', 'Louis-Napoléon Bonaparte', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'En quelle année a eu lieu la Révolution française ?', '1789', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'vrai_faux', 'facile', 'Napoléon mesurait environ 1m50.', 'Faux, il mesurait environ 1m68, dans la moyenne de l''époque', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'Quel mur a séparé Berlin de 1961 à 1989 ?', 'Le mur de Berlin', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'Quelle civilisation a construit Machu Picchu ?', 'Les Incas', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'Quel roi de France est resté sur le trône le plus longtemps ?', 'Louis XIV', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'En quelle année Constantinople est-elle tombée aux mains des Ottomans ?', '1453', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'facile', 'Quel est le plus long fleuve de France ?', 'La Loire', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'facile', 'Quelle est la capitale de l''Italie ?', 'Rome', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quel pays a le plus grand nombre de fuseaux horaires terrestres ?', 'La France (grâce à ses territoires d''outre-mer)', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quelle chaîne de montagnes sépare l''Europe et l''Asie ?', 'L''Oural', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quelle est la capitale du Bhoutan ?', 'Thimphou', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quel est le seul pays traversé par l''équateur et le tropique du Capricorne ?', 'Le Brésil', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'facile', 'Quel est le symbole chimique de l''eau ?', 'H2O', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'vrai_faux', 'facile', 'Le soleil est une étoile.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'moyen', 'Combien d''os compte le squelette humain adulte ?', '206', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'moyen', 'Quelle planète est surnommée la planète rouge ?', 'Mars', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'difficile', 'Quel scientifique a formulé la théorie de la relativité générale ?', 'Albert Einstein', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'difficile', 'Quel est le seul métal liquide à température ambiante ?', 'Le mercure', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'facile', 'Tous les combien d''années ont lieu les Jeux Olympiques d''été ?', '4 ans', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'moyen', 'Quel pays a remporté la Coupe du monde de football en 2018 ?', 'La France', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'difficile', 'Quel cycliste français a gagné 5 Tours de France ?', 'Bernard Hinault', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'facile', 'Quel groupe britannique a chanté ''Hey Jude'' ?', 'The Beatles', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'moyen', 'Quel instrument Mozart maîtrisait-il dès l''âge de 5 ans ?', 'Le clavecin/piano', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'difficile', 'Quel compositeur a écrit ''Les Quatre Saisons'' ?', 'Vivaldi', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'facile', 'Qui a peint la Joconde ?', 'Léonard de Vinci', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'moyen', 'Dans quel musée parisien se trouve la Joconde ?', 'Le Louvre', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'difficile', 'Quel mouvement artistique Salvador Dalí a-t-il incarné ?', 'Le surréalisme', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'facile', 'Les pieuvres ont trois cœurs.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'moyen', 'Le miel ne périme jamais.', 'Vrai, dans de bonnes conditions de conservation', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'moyen', 'Un escargot peut dormir jusqu''à 3 ans.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'reponse_libre', 'difficile', 'Quel est l''animal terrestre le plus rapide sur courte distance ?', 'Le guépard', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'facile', 'Quel est le nom du sorcier créé par J.K. Rowling ?', 'Harry Potter', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'moyen', 'Dans quel film culte entend-on ''Que la Force soit avec toi'' ?', 'Star Wars', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'difficile', 'Quel réalisateur a mis en scène ''Pulp Fiction'' ?', 'Quentin Tarantino', NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'facile', 'Qu''est-ce qui te rend vraiment heureux/se au quotidien ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'facile', 'Préfères-tu avoir raison ou être en paix ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Penses-tu que l''être humain est fondamentalement bon ou égoïste ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Est-ce que la fin justifie toujours les moyens ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Le bonheur est-il un choix ou une conséquence des circonstances ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', 'Si l''intelligence artificielle devenait consciente, aurait-elle des droits ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', 'Peut-on vraiment aimer quelqu''un sans jamais le/la comprendre entièrement ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', '« Je pense, donc je suis. » - Descartes. Que penses-tu de cette phrase ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'facile', 'Penses-tu que voter est un devoir ou un droit facultatif ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'moyen', 'Que penses-tu de la limitation du nombre de mandats présidentiels ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'moyen', 'Es-tu pour ou contre la peine de mort ? Pourquoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'difficile', 'Penses-tu que les réseaux sociaux devraient être davantage régulés par la loi ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'difficile', 'Que penses-tu du revenu universel comme politique économique ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'facile', 'Quel est notre premier voyage ensemble ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'moyen', 'Quel a été le moment où tu as su que c''était du sérieux entre nous ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'amis', 'reponse_libre', 'facile', 'Quelle est la première chose qu''on a faite ensemble ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'amis', 'reponse_libre', 'moyen', 'Quel voyage ou sortie avec le groupe t''a le plus marqué ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : film ou série ?', NULL, '{"choix":["Film","Série"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : petit-déjeuner sucré ou salé ?', NULL, '{"choix":["Sucré","Salé"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'moyen', 'Tu préfères : être riche et seul, ou pauvre et entouré ?', NULL, '{"choix":["Riche et seul","Pauvre et entouré"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'couple', 'qcm', 'moyen', 'Tu préfères : recevoir des mots doux ou des câlins ?', NULL, '{"choix":["Mots doux","Câlins"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'difficile', 'Tu préfères : connaître ton avenir ou ton passé oublié ?', NULL, '{"choix":["Ton avenir","Ton passé oublié"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'facile', 'Qui de nous deux est le/la plus romantique ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'moyen', 'Qui de nous deux dépense le plus d''argent en impulsif ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'amis', 'qcm', 'facile', 'Qui du groupe raconte le mieux les histoires ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'amis', 'qcm', 'moyen', 'Qui du groupe serait le plus susceptible de survivre à une apocalypse zombie ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'facile', 'Si tu pouvais avoir un super-pouvoir totalement inutile, lequel choisirais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'moyen', 'Si tu devais manger un seul plat pour le reste de ta vie, lequel serait-ce ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'difficile', 'Si tu pouvais vivre dans un film ou une série, laquelle choisirais-tu et pourquoi ?', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'defis_gages', 'couple', 'action', 'moyen', 'Raconte à ton/ta partenaire un souvenir gênant que tu ne lui as jamais raconté.', NULL, NULL, NULL, NULL, 90),
('defi', 'jeux_ensemble', 'defis_gages', 'amis', 'action', 'facile', 'Fais 10 pompes ou raconte une blague au groupe.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'defis_gages', 'couple', 'action', 'difficile', 'Danse un slow avec ton/ta partenaire sans musique pendant 30 secondes.', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'defis_gages', 'solo', 'action', 'moyen', 'Envoie un message à quelqu''un que tu n''as pas contacté depuis longtemps.', NULL, NULL, NULL, NULL, 180),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'facile', 'On me lance, je vole sans ailes, je pleure sans yeux. Qui suis-je ?', 'Un nuage', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'moyen', 'Un fermier a 17 moutons. Toutes meurent sauf 9. Combien lui en reste-t-il ?', '9', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'moyen', 'Qu''est-ce qui a des clés mais n''ouvre aucune porte ?', 'Un piano', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'code_4_chiffres', 'difficile', 'Code à 4 chiffres : tous différents, en ordre décroissant, la somme fait 18.', '6543', NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'moyen', 'Si tu pouvais donner un seul conseil à ton toi de 15 ans, lequel serait-ce ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'difficile', 'Penses-tu que tout arrive pour une raison ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'enfance', 'tous', 'reponse_libre', 'facile', 'Quel était ton jeu préféré quand tu étais enfant ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'enfance', 'tous', 'reponse_libre', 'moyen', 'Quel adulte a le plus marqué ton enfance et pourquoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'reves', 'tous', 'reponse_libre', 'facile', 'Quelle destination de voyage fait le plus rêver ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'reves', 'tous', 'reponse_libre', 'difficile', 'Si l''argent n''était pas un problème, quel métier ferais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'peurs', 'tous', 'reponse_libre', 'facile', 'As-tu une phobie ? Laquelle ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'peurs', 'tous', 'reponse_libre', 'difficile', 'Qu''est-ce qui te fait le plus peur dans le fait de vieillir ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'moyen', 'Quelle qualité admires-tu le plus chez les autres ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'difficile', 'Pardonnerais-tu une trahison si la personne changeait vraiment ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'facile', 'C''est quoi pour toi une preuve d''amour au quotidien ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'difficile', 'Qu''est-ce que je pourrais faire pour te rendre encore plus heureux/se ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amitie', 'amis', 'reponse_libre', 'facile', 'Quelle est la qualité qui définit le mieux notre amitié ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amitie', 'amis', 'reponse_libre', 'difficile', 'Y a-t-il quelque chose que tu n''as jamais osé me dire ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'futur', 'tous', 'reponse_libre', 'facile', 'Quel est ton projet le plus excitant pour l''année qui vient ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'futur', 'couple', 'reponse_libre', 'difficile', 'Comment imagines-tu notre vie dans 10 ans ?', NULL, NULL, NULL, NULL, 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'facile', 'Quel fruit du démon Luffy a-t-il mangé ?', 'Le fruit du Gomu Gomu (Nika)', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'moyen', 'Qui est le premier second de Luffy à rejoindre l''équipage ?', 'Zoro', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'difficile', 'Quel est le vrai nom de Portgas D. Ace en lien avec son père ?', 'Fils de Gol D. Roger', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'facile', 'Quel est le rêve de Naruto ?', 'Devenir Hokage', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'moyen', 'Quel clan possède le Sharingan ?', 'Le clan Uchiha', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'difficile', 'Comment s''appelle la technique interdite qui invoque le dieu de la mort ?', 'Shiki Fūjin', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'facile', 'Quel est le nom de famille d''Eren ?', 'Jaeger', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'difficile', 'Comment s''appelle le pouvoir qui permet de contrôler la mémoire des Titans ?', 'Le Titan Originel', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'demon_slayer', 'tous', 'reponse_libre', 'facile', 'Quel est le métier du héros Tanjiro avant de devenir pourfendeur ?', 'Marchand de charbon', NULL, NULL, 'Demon Slayer', 30),
('question', 'manga', 'demon_slayer', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom du style de respiration de Tanjiro ?', 'Respiration de l''eau (puis du feu/Hinokami)', NULL, NULL, 'Demon Slayer', 30),
('question', 'manga', 'fairy_tail', 'tous', 'reponse_libre', 'facile', 'Quel animal magique accompagne Happy ?', 'C''est un chat volant lui-même', NULL, NULL, 'Fairy Tail', 30),
('question', 'manga', 'fairy_tail', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom du dragon qui a élevé Natsu ?', 'Igneel', NULL, NULL, 'Fairy Tail', 30),
('question', 'manga', 'my_hero_academia', 'tous', 'reponse_libre', 'facile', 'Quel est le nom du pouvoir principal de Deku ?', 'One For All', NULL, NULL, 'My Hero Academia', 30),
('question', 'manga', 'my_hero_academia', 'tous', 'reponse_libre', 'difficile', 'Qui est le premier détenteur connu de One For All ?', 'All For One (avant qu''il ne le vole)', NULL, NULL, 'My Hero Academia', 30),
('question', 'manga', 'jujutsu_kaisen', 'tous', 'reponse_libre', 'facile', 'Quel objet maudit Yuji avale-t-il au début de l''histoire ?', 'Un doigt de Sukuna', NULL, NULL, 'Jujutsu Kaisen', 30),
('question', 'manga', 'jujutsu_kaisen', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom de la technique innée de Gojo ?', 'Illimité (Muryōkūsho / Infinity)', NULL, NULL, 'Jujutsu Kaisen', 30),
('question', 'manga', 'death_note', 'tous', 'reponse_libre', 'facile', 'Comment s''appelle le shinigami qui donne le carnet à Light ?', 'Ryuk', NULL, NULL, 'Death Note', 30),
('question', 'manga', 'death_note', 'tous', 'reponse_libre', 'difficile', 'Quel est le vrai nom de L ?', 'L Lawliet', NULL, NULL, 'Death Note', 30),
('question', 'manga', 'dragon_ball', 'tous', 'reponse_libre', 'facile', 'Combien de boules de cristal faut-il réunir pour invoquer Shenron ?', '7', NULL, NULL, 'Dragon Ball', 30),
('question', 'manga', 'dragon_ball', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom de la planète d''origine de Vegeta ?', 'Végéta (anciennement Plante)', NULL, NULL, 'Dragon Ball', 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'Quel roi de France est surnommé le Roi Soleil ?', 'Louis XIV', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'En quelle année s''est terminée la Seconde Guerre mondiale ?', '1945', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'Quel bateau réputé insubmersible a coulé en 1912 ?', 'Le Titanic', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'vrai_faux', 'facile', 'Les pyramides d''Égypte ont été construites par des esclaves selon les découvertes archéologiques récentes.', 'Faux, plutôt par des ouvriers payés', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'Quel empereur romain a légalisé le christianisme ?', 'Constantin', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'Quelle reine d''Égypte est célèbre pour sa relation avec Jules César et Marc Antoine ?', 'Cléopâtre', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'Quel événement a déclenché la Seconde Guerre mondiale en Europe ?', 'L''invasion de la Pologne par l''Allemagne', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'Quelle bataille a marqué la défaite finale de Napoléon ?', 'Waterloo', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'Quel explorateur portugais a été le premier à atteindre l''Inde par la mer ?', 'Vasco de Gama', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'Quelle dynastie chinoise a fait construire la majeure partie de la Grande Muraille actuelle ?', 'La dynastie Ming', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'facile', 'Quel est le plus grand désert chaud du monde ?', 'Le Sahara', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'facile', 'Quelle est la capitale de l''Espagne ?', 'Madrid', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'facile', 'Quel pays a la forme d''une botte ?', 'L''Italie', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quelle est la plus haute montagne du monde ?', 'L''Everest', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quel est le pays le plus peuplé du monde en 2024 ?', 'L''Inde', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quel détroit sépare l''Europe de l''Afrique ?', 'Le détroit de Gibraltar', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quelle est la capitale de la Mongolie ?', 'Oulan-Bator', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quel est le plus petit pays du monde ?', 'Le Vatican', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quel fleuve traverse à la fois l''Égypte et le Soudan ?', 'Le Nil', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'facile', 'Quelle planète est la plus proche du soleil ?', 'Mercure', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'facile', 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?', 'Le CO2', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'vrai_faux', 'facile', 'Les chauves-souris sont aveugles.', 'Faux, elles voient mais utilisent aussi l''écholocation', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'moyen', 'Quel organe humain produit l''insuline ?', 'Le pancréas', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'moyen', 'Combien de temps la lumière du soleil met-elle à atteindre la Terre ?', 'Environ 8 minutes', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'moyen', 'Quel savant a découvert la pénicilline ?', 'Alexander Fleming', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'difficile', 'Quelle particule est responsable de la masse des autres particules selon le modèle standard ?', 'Le boson de Higgs', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom du processus par lequel les étoiles produisent de l''énergie ?', 'La fusion nucléaire', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'facile', 'Quel film raconte l''histoire d''un lion nommé Simba ?', 'Le Roi Lion', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'moyen', 'Quel réalisateur a créé la saga ''Le Seigneur des Anneaux'' au cinéma ?', 'Peter Jackson', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'difficile', 'Quel film a remporté l''Oscar du meilleur film en 2020, une première pour un film non anglophone ?', 'Parasite', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'facile', 'Qui a écrit ''Les Misérables'' ?', 'Victor Hugo', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'moyen', 'Quel auteur russe a écrit ''Crime et Châtiment'' ?', 'Dostoïevski', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'difficile', 'Quel écrivain a inventé le personnage de Sherlock Holmes ?', 'Arthur Conan Doyle', NULL, NULL, NULL, 30),
('question', 'general', 'gastronomie', 'tous', 'reponse_libre', 'facile', 'De quel pays vient la pizza margherita ?', 'L''Italie', NULL, NULL, NULL, 30),
('question', 'general', 'gastronomie', 'tous', 'reponse_libre', 'moyen', 'Quel ingrédient donne sa couleur verte au pesto ?', 'Le basilic', NULL, NULL, NULL, 30),
('question', 'general', 'gastronomie', 'tous', 'reponse_libre', 'difficile', 'Quel fromage français porte le même nom qu''une ville de Normandie ?', 'Le camembert', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'facile', 'Dans quel sport utilise-t-on une raquette et un volant ?', 'Le badminton', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'moyen', 'Combien de temps dure un match de basket NBA (temps réglementaire) ?', '48 minutes', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'difficile', 'Quel pays a inventé le sport du rugby ?', 'L''Angleterre', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'facile', 'Quel chanteur est surnommé le ''roi de la pop'' ?', 'Michael Jackson', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'moyen', 'Quel groupe suédois a chanté ''Dancing Queen'' ?', 'ABBA', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'difficile', 'Quel compositeur allemand est l''auteur de la ''Marche Nuptiale'' la plus connue ?', 'Mendelssohn (ou Wagner selon la version)', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'facile', 'Quel artiste a peint ''La Nuit étoilée'' ?', 'Van Gogh', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'moyen', 'Quel sculpteur a créé la statue du ''Penseur'' ?', 'Auguste Rodin', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'difficile', 'Quel architecte a conçu la Sagrada Familia à Barcelone ?', 'Antoni Gaudí', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'facile', 'Les bananes sont classées comme des baies.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'moyen', 'Un jour sur Vénus est plus long qu''une année sur Vénus.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'difficile', 'Le cœur d''une crevette se trouve dans sa tête.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'facile', 'Quel est le nom du jouet cow-boy dans ''Toy Story'' ?', 'Woody', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'moyen', 'Quelle console de jeu a popularisé le personnage Mario ?', 'La Nintendo (NES)', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'difficile', 'Quel jeu vidéo est considéré comme le premier jeu vidéo de l''histoire (années 1950-60) ?', 'Tennis for Two ou Spacewar! selon la définition', NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'facile', 'Qu''est-ce qui te fait te sentir vraiment toi-même ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'facile', 'Préfères-tu vivre 100 ans sans amour ou 50 ans avec ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Penses-tu que le destin existe ou que tout est le fruit du hasard ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Est-ce qu''un mensonge par omission est aussi grave qu''un mensonge direct ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Peut-on être heureux seul, sans lien social ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', 'Si tu pouvais effacer un souvenir douloureux, le ferais-tu, même s''il t''a construit ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', '« On ne se baigne jamais deux fois dans le même fleuve. » - Héraclite. Qu''en penses-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', 'La liberté totale rend-elle vraiment heureux ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'facile', 'Penses-tu que l''école devrait être obligatoire jusqu''à un âge plus tardif ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'moyen', 'Que penses-tu de l''idée d''une taxe carbone plus élevée pour les entreprises polluantes ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'moyen', 'Es-tu pour ou contre la légalisation de l''euthanasie ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'difficile', 'Penses-tu que les grandes entreprises technologiques ont trop de pouvoir aujourd''hui ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'difficile', 'Que penses-tu de l''idée de réduire la semaine de travail à 4 jours par la loi ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'facile', 'Quel est le cadeau qui t''a le plus touché de ma part ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'moyen', 'Quelle dispute nous a le plus rapprochés au final ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'difficile', 'Quel moment difficile qu''on a traversé ensemble t''a le plus fait grandir ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'amis', 'reponse_libre', 'moyen', 'Quelle bêtise qu''on a faite ensemble te fait encore rire aujourd''hui ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'amis', 'reponse_libre', 'difficile', 'Y a-t-il eu un moment où notre amitié aurait pu se briser ? Comment on l''a dépassé ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : plage ou piscine ?', NULL, '{"choix":["Plage","Piscine"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : chien ou chat ?', NULL, '{"choix":["Chien","Chat"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : soirée cocooning ou soirée festive ?', NULL, '{"choix":["Cocooning","Festive"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'moyen', 'Tu préfères : perdre l''odorat ou le goût ?', NULL, '{"choix":["L''odorat","Le goût"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'couple', 'qcm', 'moyen', 'Tu préfères : qu''on économise pour un gros projet ou qu''on profite plus au quotidien ?', NULL, '{"choix":["Économiser","Profiter au quotidien"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'difficile', 'Tu préfères : vivre 1000 ans seul ou 80 ans entouré ?', NULL, '{"choix":["1000 ans seul","80 ans entouré"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'difficile', 'Tu préfères : ne plus jamais mentir ou toujours savoir quand on te ment ?', NULL, '{"choix":["Ne plus jamais mentir","Toujours savoir"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'facile', 'Qui de nous deux met le plus de temps à se préparer ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'moyen', 'Qui de nous deux pardonne le plus facilement ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'difficile', 'Qui de nous deux ferait le plus de sacrifices pour l''autre ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'amis', 'qcm', 'moyen', 'Qui du groupe garde le mieux les secrets ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'amis', 'qcm', 'difficile', 'Qui du groupe changerait le plus si il/elle devenait riche du jour au lendemain ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'facile', 'Si tu étais une saison, laquelle serais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'facile', 'Quel super-héros ferait le pire coloc ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'moyen', 'Si les animaux pouvaient parler, lequel serait le plus impoli ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'moyen', 'Si tu devais fonder une religion absurde, quel serait son unique commandement ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'difficile', 'Si l''humanité devait tout recommencer avec 10 objets seulement, lesquels garderais-tu ?', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'defis_gages', 'couple', 'action', 'facile', 'Fais un massage des épaules de 2 minutes à ton/ta partenaire.', NULL, NULL, NULL, NULL, 120),
('defi', 'jeux_ensemble', 'defis_gages', 'couple', 'action', 'moyen', 'Écris 3 choses que tu admires chez ton/ta partenaire et lis-les à voix haute.', NULL, NULL, NULL, NULL, 90),
('defi', 'jeux_ensemble', 'defis_gages', 'amis', 'action', 'moyen', 'Chante le refrain de ta chanson préférée devant le groupe.', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'defis_gages', 'amis', 'action', 'difficile', 'Improvise une histoire drôle avec 3 mots donnés par le groupe.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'defis_gages', 'solo', 'action', 'facile', 'Note 3 choses pour lesquelles tu es reconnaissant aujourd''hui.', NULL, NULL, NULL, NULL, 90),
('defi', 'jeux_ensemble', 'defis_gages', 'solo', 'action', 'difficile', 'Fais quelque chose de gentil pour un inconnu aujourd''hui.', NULL, NULL, NULL, NULL, 600),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'facile', 'Je grandis quand tu me nourris, mais je meurs si tu me donnes de l''eau. Que suis-je ?', 'Le feu', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'facile', 'J''ai des dents mais je ne mords pas. Qui suis-je ?', 'Un peigne', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'moyen', 'Deux pères et deux fils partagent 3 pommes, chacun en a une entière. Comment est-ce possible ?', 'Ce sont un grand-père, un père et un fils (3 personnes)', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'moyen', 'Plus je suis grand, moins je pèse lourd. Que suis-je ?', 'Un trou (encore) ou une ombre selon la variante', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'difficile', 'Trois interrupteurs commandent une ampoule dans une autre pièce, tu ne peux entrer qu''une fois. Comment trouver le bon interrupteur ?', 'Allumer le 1er, attendre, l''éteindre et allumer le 2e, puis entrer : chaude+éteinte=1er, allumée=2e, froide+éteinte=3e', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'code_4_chiffres', 'difficile', 'Code à 4 chiffres : c''est une année entre 1900 et 2000, divisible par 8, se terminant par 6.', '1936', NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'facile', 'Si demain était ton dernier jour, que ferais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'moyen', 'Penses-tu qu''on choisit vraiment qui on aime ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'difficile', 'Est-ce que le temps guérit vraiment toutes les blessures ?', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'petits_jeux_cooperatifs', 'couple', 'action', 'moyen', 'Ensemble, écrivez une courte histoire en alternant une phrase chacun, sans vous concerter.', NULL, NULL, NULL, NULL, 180),
('defi', 'jeux_ensemble', 'petits_jeux_cooperatifs', 'amis', 'action', 'moyen', 'En équipe, trouvez 10 mots qui commencent par la même lettre en 60 secondes.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'petits_jeux_competitifs', 'couple', 'action', 'facile', 'Duel de pierre-feuille-ciseaux en 3 manches gagnantes.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'petits_jeux_competitifs', 'amis', 'action', 'moyen', 'Chacun écrit 3 films sur papier, le groupe doit deviner qui a écrit quoi.', NULL, NULL, NULL, NULL, 180),
('question', 'jeux_ensemble', 'questions_souvenir', 'couple', 'reponse_libre', 'moyen', 'Quelle chanson te fait immédiatement penser à nous ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'questions_souvenir', 'amis', 'reponse_libre', 'moyen', 'Quel lieu est associé à un super souvenir avec le groupe ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'enfance', 'tous', 'reponse_libre', 'moyen', 'Quel était ton rêve de métier quand tu étais petit·e ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'enfance', 'tous', 'reponse_libre', 'difficile', 'Y a-t-il un souvenir d''enfance que tu n''as jamais raconté à personne ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'reves', 'tous', 'reponse_libre', 'moyen', 'Quel talent aimerais-tu développer si tu avais plus de temps ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'reves', 'tous', 'reponse_libre', 'difficile', 'Quel rêve as-tu abandonné et regrettes-tu de l''avoir fait ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'peurs', 'tous', 'reponse_libre', 'moyen', 'Qu''est-ce qui te met le plus mal à l''aise socialement ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'peurs', 'tous', 'reponse_libre', 'difficile', 'Quelle est la chose que tu redoutes le plus de perdre ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'facile', 'Quelle est la qualité que tu détestes le plus chez les gens ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'moyen', 'Est-ce que tu penses que l''honnêteté doit toujours passer avant la gentillesse ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'difficile', 'Y a-t-il une règle que tu enfreindrais pour protéger quelqu''un que tu aimes ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'facile', 'Quel geste tout simple te fait fondre à chaque fois ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'moyen', 'Qu''est-ce qui a changé dans notre relation depuis le début, en bien ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'difficile', 'Y a-t-il un besoin que tu n''exprimes pas assez dans notre couple ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amitie', 'amis', 'reponse_libre', 'moyen', 'Qu''est-ce que tu changerais dans notre façon de communiquer ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amitie', 'amis', 'reponse_libre', 'difficile', 'T''arrive-t-il de te comparer à moi ? Sur quoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'futur', 'tous', 'reponse_libre', 'moyen', 'Quel est ton plus grand objectif pour les 5 prochaines années ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'futur', 'amis', 'reponse_libre', 'difficile', 'Comment imagines-tu notre amitié dans 20 ans ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'quotidien', 'tous', 'reponse_libre', 'facile', 'Quel est ton petit plaisir du quotidien préféré ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'quotidien', 'couple', 'reponse_libre', 'moyen', 'Quelle habitude de la maison aimerais-tu qu''on change ensemble ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'famille', 'tous', 'reponse_libre', 'moyen', 'Quelle tradition familiale aimerais-tu garder pour plus tard ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'famille', 'couple', 'reponse_libre', 'difficile', 'Quel type de parent penses-tu être, ou aimerais-tu être ?', NULL, NULL, NULL, NULL, 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'facile', 'Comment s''appelle le sabre de Zoro le plus précieux, offert par Kuina ?', 'Wado Ichimonji', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'moyen', 'Quel est le surnom de Nico Robin dans le monde entier ?', 'L''enfant démon (puis Miss All Sunday)', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom complet de l''organisation secrète que Robin a fuie ?', 'Le Gouvernement Mondial (après la destruction d''Ohara)', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'facile', 'Quel est le nom du meilleur ami rival de Naruto ?', 'Sasuke Uchiha', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'moyen', 'Quel village Naruto représente-t-il ?', 'Konoha', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'difficile', 'Comment s''appelle le sceau utilisé pour enfermer Kurama en Naruto ?', 'Le sceau à huit trigrammes', NULL, NULL, NULL, 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'moyen', 'Quel est le nom de la meilleure amie d''enfance d''Eren ?', 'Mikasa Ackerman', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom du peuple opprimé auquel appartient Eren ?', 'Les Eldiens', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'demon_slayer', 'tous', 'reponse_libre', 'moyen', 'Combien de piliers (Hashira) protègent le corps des pourfendeurs ?', '9', NULL, NULL, 'Demon Slayer', 30),
('question', 'manga', 'demon_slayer', 'tous', 'reponse_libre', 'difficile', 'Quel démon suprême est l''antagoniste principal de la série ?', 'Muzan Kibutsuji', NULL, NULL, 'Demon Slayer', 30),
('question', 'manga', 'fairy_tail', 'tous', 'reponse_libre', 'moyen', 'Quelle magie utilise Grey Fullbuster ?', 'La magie de glace', NULL, NULL, 'Fairy Tail', 30),
('question', 'manga', 'fairy_tail', 'tous', 'reponse_libre', 'difficile', 'Quel est le symbole de la guilde Fairy Tail ?', 'Une fée avec une queue', NULL, NULL, NULL, 30),
('question', 'manga', 'my_hero_academia', 'tous', 'reponse_libre', 'moyen', 'Comment s''appelle l''école pour héros que fréquente Deku ?', 'Yuei (U.A. High School)', NULL, NULL, 'My Hero Academia', 30),
('question', 'manga', 'my_hero_academia', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom de code du héros numéro 1 avant Deku, mentor de Deku ?', 'All Might', NULL, NULL, 'My Hero Academia', 30),
('question', 'manga', 'jujutsu_kaisen', 'tous', 'reponse_libre', 'moyen', 'Quel est le nom de l''école où étudie Yuji ?', 'L''école supérieure de sorcellerie de Tokyo', NULL, NULL, 'Jujutsu Kaisen', 30),
('question', 'manga', 'chainsaw_man', 'tous', 'reponse_libre', 'facile', 'Quel démon Denji fusionne-t-il pour devenir Chainsaw Man ?', 'Pochita, le démon-tronçonneuse', NULL, NULL, 'Chainsaw Man', 30),
('question', 'manga', 'chainsaw_man', 'tous', 'reponse_libre', 'difficile', 'Quel est le métier de Denji avant de devenir chasseur de démons officiel ?', 'Chasseur de démons indépendant pour rembourser des dettes', NULL, NULL, 'Chainsaw Man', 30),
('question', 'manga', 'spy_x_family', 'tous', 'reponse_libre', 'facile', 'Quel est le nom de code de l''espion principal dans Spy x Family ?', 'Twilight', NULL, NULL, 'Spy x Family', 30),
('question', 'manga', 'spy_x_family', 'tous', 'reponse_libre', 'moyen', 'Quel pouvoir spécial possède la fille adoptive Anya ?', 'Elle peut lire dans les pensées', NULL, NULL, 'Spy x Family', 30),
('question', 'manga', 'tokyo_revengers', 'tous', 'reponse_libre', 'moyen', 'Comment le héros Takemichi voyage-t-il dans le temps ?', 'En serrant quelqu''un dans ses bras (leap corporel)', NULL, NULL, 'Tokyo Revengers', 30),
('question', 'manga', 'hunter_x_hunter', 'tous', 'reponse_libre', 'facile', 'Quel examen le héros Gon souhaite-t-il réussir au début de la série ?', 'L''examen de Hunter', NULL, NULL, 'Hunter x Hunter', 30),
('question', 'manga', 'hunter_x_hunter', 'tous', 'reponse_libre', 'difficile', 'Comment s''appelle le système de pouvoirs unique à Hunter x Hunter ?', 'Le Nen', NULL, NULL, 'Hunter x Hunter', 30),
('question', 'manga', 'bleach', 'tous', 'reponse_libre', 'facile', 'Quel est le nom du sabre-esprit d''Ichigo ?', 'Zangetsu', NULL, NULL, 'Bleach', 30),
('question', 'manga', 'bleach', 'tous', 'reponse_libre', 'difficile', 'Comment appelle-t-on les âmes maléfiques que combattent les Shinigami ?', 'Les Hollows', NULL, NULL, 'Bleach', 30),
('question', 'manga', 'dragon_ball', 'tous', 'reponse_libre', 'moyen', 'Quel est le nom du maître d''arts martiaux de Goku enfant ?', 'Maître Roshi', NULL, NULL, 'Dragon Ball', 30),
('question', 'manga', 'dragon_ball', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom de la transformation ultime au-delà du Super Saiyan classique révélée contre Freezer ?', 'Le Super Saiyan', NULL, NULL, 'Dragon Ball', 30),
('question', 'manga', 'death_note', 'tous', 'reponse_libre', 'moyen', 'Quelle règle du Death Note limite la cause de mort si rien n''est précisé ?', 'La personne meurt d''une crise cardiaque', NULL, NULL, NULL, 30),
('question', 'manga', 'code_geass', 'tous', 'reponse_libre', 'moyen', 'Quel pouvoir possède Lelouch grâce au Geass ?', 'Le pouvoir d''ordonner absolument (contrôle mental à usage unique par personne)', NULL, NULL, 'Code Geass', 30),
('question', 'manga', 'tokyo_ghoul', 'tous', 'reponse_libre', 'moyen', 'Que devient le héros Kaneki après sa transplantation d''organe ?', 'Un semi-goule', NULL, NULL, 'Tokyo Ghoul', 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'Quel monument parisien a été construit pour l''Exposition universelle de 1889 ?', 'La Tour Eiffel', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'Quelle reine de France est surnommée ''l''Autrichienne'' ?', 'Marie-Antoinette', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'Quel traité a mis fin à la guerre de Trente Ans en 1648 ?', 'Le traité de Westphalie', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'vrai_faux', 'moyen', 'La Statue de la Liberté a été offerte par la France aux États-Unis.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'facile', 'Quel continent abrite le plus de pays au monde ?', 'L''Afrique', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quelle mer sépare la Grèce de la Turquie ?', 'La mer Égée', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quel pays possède le plus de fuseaux horaires en comptant seulement son territoire continu ?', 'La Russie', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'facile', 'Quel est l''organe qui pompe le sang dans le corps ?', 'Le cœur', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'moyen', 'Quelle est la vitesse de la lumière dans le vide (arrondie) ?', '300 000 km/s', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'difficile', 'Quel chimiste a créé le tableau périodique des éléments ?', 'Dmitri Mendeleïev', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'facile', 'Combien de joueurs composent une équipe de volley-ball sur le terrain ?', '6', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'moyen', 'Dans quel pays sont nés les Jeux Olympiques antiques ?', 'La Grèce', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'difficile', 'Quel nageur a remporté 23 médailles d''or olympiques, record absolu ?', 'Michael Phelps', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'facile', 'Combien de cordes possède une guitare classique ?', '6', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'moyen', 'Quel festival de musique électronique a lieu chaque année à Belgique et s''appelle ''Tomorrowland'' ?', 'Tomorrowland', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'difficile', 'Quel opéra de Mozart met en scène Don Juan ?', 'Don Giovanni', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'moyen', 'Quel peintre est associé au mouvement impressionniste et au tableau ''Impression, soleil levant'' ?', 'Claude Monet', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'difficile', 'Quel artiste a créé la fontaine ''Fountain'' (un urinoir signé) en 1917 ?', 'Marcel Duchamp', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'facile', 'Les girafes n''ont que 7 vertèbres cervicales, comme les humains.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'moyen', 'On peut entendre la couleur du ciel changer selon les saisons (illusion connue).', 'Faux, c''est une fausse affirmation', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'difficile', 'Le mont Everest grandit chaque année de quelques millimètres.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'facile', 'Quel studio a créé Mickey Mouse ?', 'Disney', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'moyen', 'Quel acteur incarne Iron Man dans l''univers Marvel (MCU) ?', 'Robert Downey Jr.', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'difficile', 'Quel film d''animation japonais de Miyazaki a remporté l''Oscar du meilleur film d''animation en 2003 ?', 'Le Voyage de Chihiro', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'facile', 'Qui a écrit la saga ''Harry Potter'' ?', 'J.K. Rowling', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'moyen', 'Quel auteur français a écrit ''Le Petit Prince'' ?', 'Antoine de Saint-Exupéry', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'difficile', 'Quel roman de Camus commence par ''Aujourd''hui, maman est morte'' ?', 'L''Étranger', NULL, NULL, NULL, 30),
('question', 'general', 'gastronomie', 'tous', 'reponse_libre', 'facile', 'Quel pays est réputé pour les sushis ?', 'Le Japon', NULL, NULL, NULL, 30),
('question', 'general', 'gastronomie', 'tous', 'reponse_libre', 'moyen', 'Quelle épice est extraite du pistil d''une fleur et coûte très cher ?', 'Le safran', NULL, NULL, NULL, 30),
('question', 'general', 'gastronomie', 'tous', 'reponse_libre', 'difficile', 'Quel plat français traditionnel utilise des escargots ?', 'Les escargots de Bourgogne', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'facile', 'Quelle série met en scène des dragons et le royaume de Westeros ?', 'Game of Thrones', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'moyen', 'Quel réseau social a été fondé par Mark Zuckerberg ?', 'Facebook', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'difficile', 'Quel jeu vidéo de construction en blocs a été créé par Markus Persson (Notch) ?', 'Minecraft', NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'facile', 'Qu''est-ce que la réussite signifie vraiment pour toi ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Penses-tu qu''on peut changer profondément de personnalité, ou reste-t-on toujours le/la même ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Est-ce que la jalousie est toujours un signe d''amour, ou un défaut à combattre ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', 'Si on pouvait vivre éternellement en bonne santé, est-ce que ce serait souhaitable ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', '« La vie est ce qui arrive pendant qu''on fait d''autres projets. » Qu''en penses-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'facile', 'Penses-tu que les jeunes s''intéressent assez à la politique aujourd''hui ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'moyen', 'Que penses-tu de l''idée d''abaisser l''âge du droit de vote à 16 ans ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'difficile', 'Penses-tu que la mondialisation a fait plus de bien que de mal ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'facile', 'Quelle est notre chanson préférée en tant que couple ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'amis', 'reponse_libre', 'facile', 'Quel surnom ridicule quelqu''un du groupe a-t-il déjà eu ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : lire un livre ou regarder un film ?', NULL, '{"choix":["Lire un livre","Regarder un film"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'moyen', 'Tu préfères : être toujours en retard ou toujours trop en avance ?', NULL, '{"choix":["Toujours en retard","Toujours en avance"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'couple', 'qcm', 'difficile', 'Tu préfères : qu''on ait moins d''argent mais plus de temps ensemble, ou l''inverse ?', NULL, '{"choix":["Moins d''argent, plus de temps","Plus d''argent, moins de temps"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'moyen', 'Qui de nous deux a le plus tendance à bouder ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'amis', 'qcm', 'difficile', 'Qui du groupe serait élu leader si on formait une équipe pour une mission ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'facile', 'Si tu étais un plat, lequel serais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'moyen', 'Si tu pouvais parler à ton animal de compagnie, que te dirait-il en premier ?', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'defis_gages', 'couple', 'action', 'facile', 'Prenez une photo rigolote ensemble tout de suite.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'defis_gages', 'amis', 'action', 'facile', 'Fais deviner un film au groupe en mimant sans parler.', NULL, NULL, NULL, NULL, 60),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'facile', 'Je suis toujours devant toi mais tu ne peux jamais m''atteindre. Que suis-je ?', 'L''avenir/le futur', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'moyen', 'Une horloge sonne 6 coups en 5 secondes. Combien de temps mettra-t-elle pour sonner 12 coups ?', '11 secondes (l''intervalle compte, pas les coups)', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'code_4_chiffres', 'difficile', 'Code à 4 chiffres : impair, croissant, la somme fait 16.', '1357', NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'moyen', 'Crois-tu qu''on garde toujours une part d''enfant en nous ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'enfance', 'tous', 'reponse_libre', 'facile', 'Quel dessin animé regardais-tu en boucle enfant ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'reves', 'tous', 'reponse_libre', 'facile', 'Si tu pouvais apprendre une langue instantanément, laquelle choisirais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'peurs', 'tous', 'reponse_libre', 'moyen', 'Quelle situation sociale te donne le plus d''anxiété ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'moyen', 'Quelle est la leçon de vie la plus importante qu''on t''ait apprise ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'moyen', 'Comment aimes-tu recevoir de l''affection au quotidien ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amitie', 'amis', 'reponse_libre', 'facile', 'Quel est le meilleur conseil que je t''ai donné ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'futur', 'tous', 'reponse_libre', 'facile', 'Quelle nouvelle expérience aimerais-tu tenter cette année ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'quotidien', 'tous', 'reponse_libre', 'moyen', 'Quel moment de la journée préfères-tu et pourquoi ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'famille', 'tous', 'reponse_libre', 'facile', 'Qui est la personne de ta famille qui t''inspire le plus ?', NULL, NULL, NULL, NULL, 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'moyen', 'Quel titre porte le futur roi des pirates selon la légende du One Piece ?', 'Celui qui trouvera le trésor One Piece', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'moyen', 'Comment s''appelle le sensei de l''équipe 7 (Naruto, Sasuke, Sakura) ?', 'Kakashi Hatake', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'moyen', 'Quel est le nom du régiment d''exploration dirigé par Erwin Smith ?', 'Le Bataillon d''exploration', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'demon_slayer', 'tous', 'reponse_libre', 'moyen', 'Quel pilier utilise la respiration du son ?', 'Tengen Uzui', NULL, NULL, 'Demon Slayer', 30),
('question', 'manga', 'my_hero_academia', 'tous', 'reponse_libre', 'moyen', 'Quel est le nom du rival principal de Deku dans sa classe ?', 'Bakugo Katsuki', NULL, NULL, 'My Hero Academia', 30),
('question', 'manga', 'jujutsu_kaisen', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom du meilleur ami de Yuji qui meurt au début de la série ?', 'Fushiguro Megumi (son camarade, pas un ami mort)', NULL, NULL, 'Jujutsu Kaisen', 30),
('question', 'manga', 'dragon_ball', 'tous', 'reponse_libre', 'moyen', 'Quel est le nom du fils aîné de Goku ?', 'Gohan', NULL, NULL, 'Dragon Ball', 30),
('question', 'manga', 'fairy_tail', 'tous', 'reponse_libre', 'difficile', 'Quel est le vrai nom de famille de Lucy, l''une des héroïnes ?', 'Heartfilia', NULL, NULL, 'Fairy Tail', 30),
('question', 'manga', 'hunter_x_hunter', 'tous', 'reponse_libre', 'moyen', 'Quel est le nom du meilleur ami de Gon rencontré pendant l''examen ?', 'Killua Zoldyck', NULL, NULL, 'Hunter x Hunter', 30),
('question', 'manga', 'bleach', 'tous', 'reponse_libre', 'moyen', 'Comment appelle-t-on le monde des Shinigami dans Bleach ?', 'La Soul Society', NULL, NULL, 'Bleach', 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'facile', 'Quel pays a offert la Statue de la Liberté aux États-Unis ?', 'La France', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'moyen', 'Quel philosophe grec a été le maître d''Alexandre le Grand ?', 'Aristote', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'difficile', 'Quelle bataille de 1815 a définitivement écarté Napoléon du pouvoir ?', 'Waterloo', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'facile', 'Quel pays a pour capitale Tokyo ?', 'Le Japon', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'moyen', 'Quelle ville italienne est célèbre pour ses canaux ?', 'Venise', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'difficile', 'Quel pays possède le plus de fjords au monde ?', 'La Norvège', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'facile', 'Quel est le plus grand mammifère du monde ?', 'La baleine bleue', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'moyen', 'Combien de chambres possède le cœur humain ?', '4', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'difficile', 'Quelle est l''unité de mesure de la force en physique ?', 'Le Newton', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'facile', 'Dans quel sport peut-on marquer un ''ace'' ?', 'Le tennis', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'moyen', 'Combien de temps dure un round de boxe professionnelle ?', '3 minutes', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'difficile', 'Quel pays a remporté le plus de Coupes du monde de football ?', 'Le Brésil (5 titres)', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'facile', 'Quel chanteur français est connu pour ''La Vie en rose'' ?', 'Édith Piaf (c''est une chanteuse)', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'moyen', 'Quel style musical est né à la Jamaïque dans les années 1960 ?', 'Le reggae', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'difficile', 'Quel compositeur est devenu totalement sourd avant d''écrire sa 9e symphonie ?', 'Beethoven', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'facile', 'Dans quelle ville se trouve la tour de Pise ?', 'Pise, en Italie', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'moyen', 'Quel street-artiste britannique reste anonyme et est connu pour ses pochoirs engagés ?', 'Banksy', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'facile', 'Les koalas dorment environ 20 heures par jour.', 'Vrai', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'vrai_faux', 'moyen', 'Il pleut des diamants sur Neptune et Uranus selon certaines théories scientifiques.', 'Vrai, c''est une hypothèse sérieuse', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'facile', 'Quel robot est le héros du film Pixar ''Wall-E'' ?', 'Wall-E', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'moyen', 'Quel acteur a incarné Jack Sparrow dans ''Pirates des Caraïbes'' ?', 'Johnny Depp', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'moyen', 'Quel auteur britannique a créé la Terre du Milieu dans ''Le Seigneur des Anneaux'' ?', 'J.R.R. Tolkien', NULL, NULL, NULL, 30),
('question', 'general', 'gastronomie', 'tous', 'reponse_libre', 'facile', 'Quel pays est réputé pour le chocolat praliné et les gaufres ?', 'La Belgique', NULL, NULL, NULL, 30),
('question', 'general', 'pop_culture', 'tous', 'reponse_libre', 'moyen', 'Quel plombier moustachu est la mascotte de Nintendo ?', 'Mario', NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'facile', 'Quelle est la plus belle qualité humaine selon toi ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'moyen', 'Penses-tu que l''argent peut vraiment acheter le bonheur, même partiellement ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'difficile', 'Est-ce que l''art a besoin d''un message pour avoir de la valeur ?', NULL, NULL, NULL, NULL, 30),
('question', 'general', 'politique_lois', 'tous', 'reponse_libre', 'moyen', 'Que penses-tu du droit de grève et de ses limites ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'couple', 'reponse_libre', 'moyen', 'Quel est le voyage qu''on n''a pas encore fait mais que tu rêves de faire avec moi ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'souvenirs', 'amis', 'reponse_libre', 'difficile', 'Quel souvenir avec le groupe garderais-tu si tu ne devais en garder qu''un seul ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'facile', 'Tu préfères : été ou hiver ?', NULL, '{"choix":["Été","Hiver"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'tu_preferes', 'tous', 'qcm', 'moyen', 'Tu préfères : perdre tous tes souvenirs ou ne plus pouvoir en créer de nouveaux ?', NULL, '{"choix":["Perdre les anciens","Ne plus en créer"]}'::jsonb, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'couple', 'qcm', 'facile', 'Qui de nous deux est le/la plus câlin·e ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'qui_de_nous_deux', 'amis', 'qcm', 'moyen', 'Qui du groupe organise le mieux les sorties ?', NULL, NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'farfelues', 'tous', 'reponse_libre', 'moyen', 'Si tu devais donner un nom de scène à ton double rockstar, ce serait quoi ?', NULL, NULL, NULL, NULL, 30),
('defi', 'jeux_ensemble', 'defis_gages', 'couple', 'action', 'moyen', 'Recréez votre première rencontre en 1 minute, façon théâtre.', NULL, NULL, NULL, NULL, 60),
('defi', 'jeux_ensemble', 'defis_gages', 'amis', 'action', 'facile', 'Fais deviner un animal en le mimant, sans bruit.', NULL, NULL, NULL, NULL, 45),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'logique', 'moyen', 'Je voyage dans le monde entier mais reste toujours dans un coin. Qui suis-je ?', 'Un timbre', NULL, NULL, NULL, 30),
('enigme', 'jeux_ensemble', 'enigmes', 'tous', 'code_4_chiffres', 'difficile', 'Code à 4 chiffres : c''est un multiple de 25, entre 7000 et 7500, avec un 5 en dernière position.', '7225', NULL, NULL, NULL, 30),
('question', 'jeux_ensemble', 'existentiel_jeu', 'tous', 'reponse_libre', 'facile', 'Qu''est-ce qui te fait dire que la vie est belle malgré tout ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'enfance', 'tous', 'reponse_libre', 'moyen', 'Quelle punition d''enfance te semble aujourd''hui complètement injuste ou drôle ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'reves', 'tous', 'reponse_libre', 'difficile', 'Si tu pouvais rencontrer une personne, vivante ou morte, qui choisirais-tu ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'peurs', 'tous', 'reponse_libre', 'facile', 'Préfères-tu affronter tes peurs ou les éviter ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'valeurs', 'tous', 'reponse_libre', 'facile', 'Quelle cause te tient le plus à cœur ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amour', 'couple', 'reponse_libre', 'facile', 'Quel est ton souvenir préféré de notre dernière semaine ensemble ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'amitie', 'amis', 'reponse_libre', 'moyen', 'Sur quoi comptes-tu le plus sur moi ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'futur', 'tous', 'reponse_libre', 'difficile', 'Quelle peur liée au futur essaies-tu de dépasser en ce moment ?', NULL, NULL, NULL, NULL, 30),
('question', 'mieux_connaitre', 'quotidien', 'tous', 'reponse_libre', 'facile', 'Quel petit rituel du matin ne pourrais-tu pas sauter ?', NULL, NULL, NULL, NULL, 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'facile', 'Comment s''appelle le grand méchant final que Luffy vise à devenir plus fort que ?', 'Le Gouvernement Mondial et les Empereurs (Yonko) selon l''arc', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'facile', 'Quel village Sasuke fuit-il pour rejoindre Orochimaru ?', 'Konoha', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'facile', 'Derrière quels murs vivent les personnages au début de la série ?', 'Mur Maria, Rose et Sina', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'demon_slayer', 'tous', 'reponse_libre', 'moyen', 'Quelle est la couleur de la lame du sabre de Tanjiro ?', 'Noire (nichirin noir)', NULL, NULL, 'Demon Slayer', 30),
('question', 'manga', 'my_hero_academia', 'tous', 'reponse_libre', 'facile', 'Comment appelle-t-on les pouvoirs spéciaux dans My Hero Academia ?', 'Les Quirks (Alters en VF)', NULL, NULL, 'My Hero Academia', 30),
('question', 'manga', 'fairy_tail', 'tous', 'reponse_libre', 'facile', 'Quel est le nom de la guilde principale de la série ?', 'Fairy Tail', NULL, NULL, 'Fairy Tail', 30),
('question', 'manga', 'dragon_ball', 'tous', 'reponse_libre', 'facile', 'Quel est le nom de la technique de destruction ultime de Goku, boule d''énergie bleue ?', 'Le Kaméhaméha', NULL, NULL, 'Dragon Ball', 30),
('question', 'manga', 'hunter_x_hunter', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom de la famille d''assassins de Killua ?', 'Les Zoldyck', NULL, NULL, 'Hunter x Hunter', 30),
('question', 'manga', 'spy_x_family', 'tous', 'reponse_libre', 'difficile', 'Quel est le nom de code de l''épouse assassin dans Spy x Family ?', 'Thorn Princess (Yor Forger)', NULL, NULL, 'Spy x Family', 30),
('question', 'manga', 'tokyo_ghoul', 'tous', 'reponse_libre', 'facile', 'De quoi se nourrissent les goules dans Tokyo Ghoul ?', 'De chair humaine', NULL, NULL, 'Tokyo Ghoul', 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom du dernier empereur byzantin, mort lors de la chute de Constantinople en 1453 ?', 'Constantin XI Paléologue', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'impossible', 'En quelle année exacte a été signé le traité de Tordesillas partageant le Nouveau Monde entre l''Espagne et le Portugal ?', '1494', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'impossible', 'Quelle est la capitale administrative des Pays-Bas (différente de la capitale constitutionnelle) ?', 'La Haye', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'impossible', 'Quel est le point culminant de l''Afrique ?', 'Le Kilimandjaro', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom du physicien qui a formulé le principe d''incertitude en mécanique quantique ?', 'Werner Heisenberg', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'impossible', 'Quelle est la demi-vie du carbone 14, utilisée pour la datation ?', 'Environ 5 730 ans', NULL, NULL, NULL, 30),
('question', 'general', 'arts', 'tous', 'reponse_libre', 'impossible', 'Quel peintre flamand a réalisé le triptyque ''Le Jardin des délices'' ?', 'Jérôme Bosch', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'impossible', 'Quel auteur japonais a écrit ''La Ballade de Narayama'' ?', 'Shichirō Fukazawa', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'impossible', 'Quelle symphonie de Beethoven est restée inachevée à sa mort ?', 'La 10e symphonie', NULL, NULL, NULL, 30),
('question', 'general', 'sport', 'tous', 'reponse_libre', 'impossible', 'Quel joueur d''échecs a été champion du monde le plus jeune de l''histoire ?', 'Garry Kasparov (à 22 ans, en 1985)', NULL, NULL, NULL, 30),
('question', 'general', 'insolite', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom du seul mammifère capable de vol soutenu ?', 'La chauve-souris', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'impossible', 'Quel pharaon égyptien a régné le plus longtemps (environ 66 ans) ?', 'Ramsès II', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'impossible', 'Quel est le seul pays au monde à avoir un drapeau non rectangulaire ?', 'Le Népal', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom de l''unité de mesure de la radioactivité dans le système international ?', 'Le Becquerel', NULL, NULL, NULL, 30),
('question', 'general', 'cinema', 'tous', 'reponse_libre', 'impossible', 'Quel film a été le premier long-métrage d''animation de l''histoire du cinéma (1917, aujourd''hui perdu) ?', 'El Apóstol (Argentine)', NULL, NULL, NULL, 30),
('question', 'general', 'litterature', 'tous', 'reponse_libre', 'impossible', 'Quel est le vrai nom de l''auteur George Orwell ?', 'Eric Arthur Blair', NULL, NULL, NULL, 30),
('question', 'general', 'musique', 'tous', 'reponse_libre', 'impossible', 'Dans quelle tonalité est écrite la 5e symphonie de Beethoven ?', 'Do mineur', NULL, NULL, NULL, 30),
('question', 'general', 'histoire', 'tous', 'reponse_libre', 'impossible', 'Quel était le nom de code de l''opération de débarquement allié en Normandie en 1944 ?', 'Overlord', NULL, NULL, NULL, 30),
('question', 'general', 'sciences', 'tous', 'reponse_libre', 'impossible', 'Quel chimiste français a formulé la loi de conservation de la masse ?', 'Antoine Lavoisier', NULL, NULL, NULL, 30),
('question', 'general', 'geographie', 'tous', 'reponse_libre', 'impossible', 'Quelle est la fosse océanique la plus profonde du monde ?', 'La fosse des Mariannes', NULL, NULL, NULL, 30),
('question', 'manga', 'one_piece', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom du village natal de Nico Robin, entièrement rayé de la carte ?', 'Ohara', NULL, NULL, 'One Piece', 30),
('question', 'manga', 'naruto', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom complet de la technique interdite qui invoque le dieu de la mort dans Naruto ?', 'Shiki Fūjin', NULL, NULL, 'Naruto', 30),
('question', 'manga', 'attaque_titans', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom du premier roi muré, fondateur de la lignée royale d''Eldia ?', 'Ymir Fritz', NULL, NULL, 'L''Attaque des Titans', 30),
('question', 'manga', 'hunter_x_hunter', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom de la catégorie de Nen que possède Gon (renforcement) ?', 'Kyōka (renforcement)', NULL, NULL, 'Hunter x Hunter', 30),
('question', 'manga', 'bleach', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom du roi spirituel gouvernant la Soul Society dans Bleach ?', 'Le Roi des Âmes (Soul King)', NULL, NULL, 'Bleach', 30),
('question', 'manga', 'jujutsu_kaisen', 'tous', 'reponse_libre', 'impossible', 'Quel est le nom complet de la technique de Sukuna qui divise l''espace ?', 'Domaine Malléable : Cuisine Mahoraga / Dismantle-Cleave selon les techniques', NULL, NULL, 'Jujutsu Kaisen', 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'impossible', 'Quel philosophe est l''auteur du concept de ''volonté de puissance'' ?', 'Friedrich Nietzsche', NULL, NULL, NULL, 30),
('question', 'general', 'philosophie', 'tous', 'reponse_libre', 'impossible', 'Dans quel ouvrage Emmanuel Kant développe-t-il l''impératif catégorique ?', 'Fondements de la métaphysique des mœurs', NULL, NULL, NULL, 30);